version: '3.7'

services:
  flask:
    build: ./server
    volumes:
      - ./server/:/code
    ports:
      - 5000:5000
    env_file:
      - server/env.dev
    depends_on:
      - redis
    restart: "always"
  react:
    build: ./client
    volumes:
      - ./client/:/code
    ports:
      - 3000:3000
    depends_on:
      - flask
    tty: true
  redis:
    image: redis